### ISSUE TITLE
Javafx component cannot work on Macbook

### ISSUE THREAD

**Issue by SalonetheGreat** [AY1920S1-CS2113-T13-3/main#144]
<img width="1002" alt="Screenshot 2019-11-01 at 16 48 52" src="https://user-images.githubusercontent.com/42372396/68013336-93361f80-fcc7-11e9-8cc6-a2474daaebca.png">
<img width="488" alt="Screenshot 2019-11-01 at 16 51 50" src="https://user-images.githubusercontent.com/42372396/68013465-f0ca6c00-fcc7-11e9-9928-9f759a167b8a.png">
The javafx component doesn't work on my Macbook. Above are the details when I run the jar file.

**Comment by TanYiXiang** [comment]
Fixed via #155

**Comment by E0310898** [comment]
Fixed via #155, check build.gradle for the update needed.
