### ISSUE TITLE
Convert all magic strings and numbers

### ISSUE THREAD

**Issue by fauzt** [AY1920S1-CS2113-T13-3/main#188]
There's still bit and pieces of magic strings and numbers around the code.

General rule of thumb to deal with them:
If there's a fixed number of them and are closely related to the class using them and nowhere else, set them as an inner enum class. (eg. Gender enum[MALE, FEMALE, NONBINARY] for Person class, Gender has no use outside of Person context)

If they're being used by a lot of classes (eg. Flags for Parsers, Commands), set them as an outside enum class.

**Comment by E0310898** [comment]
Completed by #210
