### ISSUE TITLE
Strange error caused while creating deadline

### ISSUE THREAD

**Issue by assman** [AY1920S1-CS2113-T13-3/main#34]
<img width="568" alt="Screen Shot 2019-09-15 at 12 31 04 AM" src="https://user-images.githubusercontent.com/14093665/64911132-7910a400-d750-11e9-9ae1-d5de01559899.png">
Duke throws error while creating deadline, however the task is still created.

**Comment by E0310898** [comment]
that was the error we were trying to fix the read and write has not been working!

**Comment by hanskw4267** [comment]
Read/write bug fixed #43

**Comment by fauzt** [comment]
issue has been fixed, the write operation should be functioning properly now
