### ISSUE TITLE
Non required object declaration

### ISSUE THREAD

**Issue by assman** [AY1920S1-CS2113-T13-3/main#35]
<img width="613" alt="Screen Shot 2019-09-15 at 12 37 24 AM" src="https://user-images.githubusercontent.com/14093665/64911208-2aafd500-d751-11e9-9bb4-b1d1b8e4ce8a.png">

All the methods of the UI class are static and they can be accessed statically using [`Ui.methodName`](url)

However, in the constructor of the Duke class, a new object of Ui is created.

**Comment by E0310898** [comment]
yes this is good can just delete the unnecessary declaration

**Comment by hanskw4267** [comment]
Issue resolved as off latest commits
