### ISSUE TITLE
Deadline switch case commented out

### ISSUE THREAD

**Issue by assman** [AY1920S1-CS2113-T13-3/main#36]
<img width="670" alt="Screen Shot 2019-09-15 at 12 52 31 AM" src="https://user-images.githubusercontent.com/14093665/64911348-343a3c80-d753-11e9-8437-c47df0670539.png">

May I ask how is the deadline parsed

**Comment by E0310898** [comment]
this is a fall through function so dont need repetitive code

**Comment by E0310898** [comment]
please see the fallthrough of switch case
it allows you to cascade code

**Comment by hanskw4267** [comment]
Issue was explained and accepted
