### ISSUE TITLE
Can't delete task

### ISSUE THREAD

**Issue by assman** [AY1920S1-CS2113-T13-3/main#44]
<img width="626" alt="Screen Shot 2019-09-15 at 2 16 46 PM" src="https://user-images.githubusercontent.com/14093665/64917494-a185b600-d7c3-11e9-9e8b-636356136e42.png">

I'm not able to delete the tasks :(

**Comment by E0310898** [comment]
I have made a fix for this bug! will be updated in the next pull request.

**Comment by fauzt** [comment]
fixed with #46
