### ISSUE TITLE
Missing DukeDatabase folder

### ISSUE THREAD

**Issue by hanskw4267** [AY1920S1-CS2113-T13-3/main#5]
forked repos will not have this folder due to the only file inside not being tracked.
just make a "DukeDatabase" folder under src folder

**Comment by hanskw4267** [comment]
i have done this.
Those that have done this, please say here, last to do it please close this issue

**Comment by assman** [comment]
✅

**Comment by E0310898** [comment]
✅

**Comment by fauzt** [comment]
✅
